### ISSUE TITLE
API for sets is missing Lost Caverns - Extended Art

### ISSUE THREAD

**Issue by rherban** [pauperbattlebox/mvb-api#44]
The /sets API doesn't have `Lost Caverns - Extended Art`:

https://www.multiversebridge.com/api/v1/sets/cs/1729
```
{
    "Message": "404 Not Found"
}
```

Yet it exists here:
https://www.cardsphere.com/sets/1729

**Comment by pauperbattlebox** [comment]
Thanks, I'll get this added shortly.

**Comment by pauperbattlebox** [comment]
This is complete.

![image](https://github.com/pauperbattlebox/mvb-api/assets/55305398/39224d61-8f34-406c-89a5-d3e8f0a749bd)
