### ISSUE TITLE
Add card ID to SetsWithCardsSchema

### ISSUE THREAD

**Issue by rherban** [pauperbattlebox/mvb-api#47]
Is it possible to add the card ID (`cards.cs_id`) to `SetsWithCardsSchema`?

This would be useful when querying the set data and populating a local cards DB without having to re-query for each card in the set.

**Comment by pauperbattlebox** [comment]
I should be able to add this, maybe behind a query param. Are you looking to do this for the /sets endpoint?

I also have some bulk endpoints available if you are looking for a specific bulk dataset. @rherban

**Comment by rherban** [comment]
Yes, I was planning on calling `https://www.multiversebridge.com/api/v1/sets/mtgjson/LCI` and the like and looping over it to import cards without hammering your API.  

The bulk endpoint might be a better option though. Where can I get more info on that?

**Comment by pauperbattlebox** [comment]
https://cdn.multiversebridge.com/mtgjson_build.json

This endpoint is updated daily with:

- cs_id
- mtgjson_id
- scryfall_id
- is_foil
- price


I can create a different bulk export if you're looking for additional fields.

**Comment by rherban** [comment]
Do you have a bulk export of card data?  

- cs_id
- name
- edition
- is_foil
- mtgjson_id
- scryfall_id
- collector_number
- mtgjson_code

I feel like I'm just missing something obvious, but calling `/sets/mtgjson/XXX` will get me one subset of card info, the bulk export will give another, and calling `/cards/cs/12345` will get the full data, but will be taxing for both of us.  

I appreciate your responses and willingness to help.

**Comment by pauperbattlebox** [comment]
I can get a bulk dump like this built out, hopefully tonight.

**Comment by pauperbattlebox** [comment]
@rherban https://cdn.multiversebridge.com/bulk.json

This is the current export. I'll work on getting this export automated nightly.

**Comment by rherban** [comment]
Thanks that works perfectly!

I still think the original request would be useful long-term, but I'll let you make that call.

**Comment by pauperbattlebox** [comment]
Cool, I'll look at that as part of upcoming rebuild. Cheers!
