### ISSUE TITLE
Request to add is_foil to all_ids.json

### ISSUE THREAD

**Issue by fast-facts** [pauperbattlebox/mvb-api#48]
Would it be possible to add the `is_foil` field to the `all_ids.json` file so that we can properly map `scryfall_id`, in conjunction with the `is_foil`, to a unique `cs_id`? Right now it maps 1 to many.

**Comment by pauperbattlebox** [comment]
@fast-facts Would this file help?

https://cdn.multiversebridge.com/mtgjson_build.json

**Comment by pauperbattlebox** [comment]
@fast-facts LOL, I knew you'd reply before I edited.

If you don't mind, what are you using this API for?

LMK if I can do anything else for ya.

**Comment by pauperbattlebox** [comment]
Gotcha, thanks @fast-facts The only other nuance would be etched foils. Scryfall uses the same ID for those as foil and non-foil. 
I'm working to have a much more detailed v2 of this platform in the coming months. Cheers!

**Comment by pauperbattlebox** [comment]
Ya, that's how Cardsphere identifies them.

This is planned for the next version of this API.

I will open a new issue for this shortly, might be able to get a work around up and running with this version.
